[package]
name = "gl"
version = "2.2.7"
authors = ["Jake W. Ireland <jakewilliami@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["cargo", "wrap_help", "derive"] }
colored = "2.1.0"
colorsys = "0.6.7"
hyperpolyglot = "0.1.7"
json = "0.12.4"
regex = "1.10.4"
tabular = "0.2.0"

