[package]
name = "gl"
version = "2.2.1"
authors = ["Jake W. Ireland <jakewilliami@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.19", features = ["help", "usage", "error-context", "wrap_help", "cargo"] }
colored = "2.0.0"
colorsys = "0.6.6"
hyperpolyglot = "0.1.7"
json = "0.12.4"
regex = "1.7.0"
tabular = "0.2.0"

